/* Liora — curated gift catalog */
window.LIORA_PRODUCTS = [
  {
    id: "rosewood-candle",
    name: "Rosewood & Amber Candle",
    price: 1299,
    compareAt: 1599,
    category: "Home",
    occasions: ["Birthday", "Anniversary", "Festive"],
    recipients: ["For Her", "For Couples"],
    personalizable: true,
    trending: true,
    bestseller: true,
    newest: false,
    stock: 42,
    rating: 4.8,
    reviews: 126,
    deliveryDays: "2–4",
    images: ["assets/products/candle-1.jpg", "assets/products/candle-2.jpg"],
    description: "A hand-poured soy candle with rosewood and warm amber notes. Includes optional engraved brass lid plate.",
    personalization: ["Engraved name on lid", "Gift message"],
  },
  {
    id: "curated-keepsake-box",
    name: "Curated Keepsake Box",
    price: 3499,
    compareAt: null,
    category: "Hampers",
    occasions: ["Anniversary", "Weddings", "Birthday"],
    recipients: ["For Her", "For Him", "For Couples"],
    personalizable: true,
    trending: true,
    bestseller: true,
    newest: true,
    stock: 18,
    rating: 4.9,
    reviews: 89,
    deliveryDays: "3–5",
    images: ["assets/products/box-1.jpg", "assets/products/box-2.jpg"],
    description: "A layered gift box with artisan chocolate, a mini candle, and a handwritten-style note card.",
    personalization: ["Custom note card", "Recipient name on ribbon"],
  },
  {
    id: "pearl-drop-necklace",
    name: "Pearl Drop Necklace",
    price: 4599,
    compareAt: 5200,
    category: "Jewelry",
    occasions: ["Anniversary", "Weddings", "Birthday"],
    recipients: ["For Her"],
    personalizable: true,
    trending: true,
    bestseller: true,
    newest: false,
    stock: 12,
    rating: 4.7,
    reviews: 64,
    deliveryDays: "4–6",
    images: ["assets/products/jewelry-1.jpg", "assets/products/jewelry-2.jpg"],
    description: "Freshwater pearl on a fine gold-tone chain. Engrave a short initial on the clasp plate.",
    personalization: ["Initial engraving", "Gift wrap"],
  },
  {
    id: "midnight-chronograph",
    name: "Midnight Chronograph Watch",
    price: 7999,
    compareAt: null,
    category: "Accessories",
    occasions: ["Birthday", "Anniversary", "Corporate"],
    recipients: ["For Him"],
    personalizable: true,
    trending: true,
    bestseller: false,
    newest: true,
    stock: 9,
    rating: 4.6,
    reviews: 41,
    deliveryDays: "3–5",
    images: ["assets/products/watch-1.jpg", "assets/products/watch-2.jpg"],
    description: "A sleek chronograph with a soft leather strap. Optional case engraving for milestones.",
    personalization: ["Case back engraving"],
  },
  {
    id: "ceramic-planter-duo",
    name: "Ceramic Planter Duo",
    price: 1899,
    compareAt: 2199,
    category: "Home",
    occasions: ["Housewarming", "Birthday", "Corporate"],
    recipients: ["For Him", "For Her", "For Couples"],
    personalizable: false,
    trending: false,
    bestseller: true,
    newest: false,
    stock: 35,
    rating: 4.5,
    reviews: 73,
    deliveryDays: "2–4",
    images: ["assets/products/plant-1.jpg", "assets/products/plant-2.jpg"],
    description: "Two matte ceramic planters styled for desks and windowsills — a living gift that lasts.",
    personalization: [],
  },
  {
    id: "monogram-mug-set",
    name: "Monogram Mug Set",
    price: 999,
    compareAt: null,
    category: "Personalized",
    occasions: ["Birthday", "Corporate", "Festive"],
    recipients: ["For Him", "For Her", "For Couples"],
    personalizable: true,
    trending: true,
    bestseller: true,
    newest: false,
    stock: 56,
    rating: 4.8,
    reviews: 210,
    deliveryDays: "3–5",
    images: ["assets/products/mug-1.jpg", "assets/products/mug-2.jpg"],
    description: "Stoneware mug pair with monogram initials — a thoughtful everyday gift.",
    personalization: ["Initials (up to 3 letters)", "Gift message"],
  },
  {
    id: "linen-photo-frame",
    name: "Linen Photo Frame",
    price: 1499,
    compareAt: null,
    category: "Home",
    occasions: ["Weddings", "Anniversary", "Birthday"],
    recipients: ["For Couples", "For Her", "For Him"],
    personalizable: true,
    trending: false,
    bestseller: false,
    newest: true,
    stock: 28,
    rating: 4.4,
    reviews: 33,
    deliveryDays: "2–4",
    images: ["assets/products/frame-1.jpg", "assets/products/frame-2.jpg"],
    description: "Linen-wrapped frame with optional engraved brass plaque for dates and names.",
    personalization: ["Date & names plaque"],
  },
  {
    id: "festive-celebration-hamper",
    name: "Festive Celebration Hamper",
    price: 5299,
    compareAt: 5999,
    category: "Hampers",
    occasions: ["Festive", "Corporate", "Weddings"],
    recipients: ["For Couples", "For Him", "For Her"],
    personalizable: true,
    trending: true,
    bestseller: true,
    newest: true,
    stock: 22,
    rating: 4.9,
    reviews: 97,
    deliveryDays: "3–6",
    images: ["assets/products/hamper-1.jpg", "assets/products/hamper-2.jpg"],
    description: "A premium festive hamper with sweets, tea, and a keepsake candle — ready for Diwali and celebrations.",
    personalization: ["Company logo card", "Custom greeting"],
  },
  {
    id: "storytime-soft-toy",
    name: "Storytime Soft Toy",
    price: 1199,
    compareAt: null,
    category: "Kids",
    occasions: ["Birthday", "Festive"],
    recipients: ["For Kids"],
    personalizable: true,
    trending: false,
    bestseller: true,
    newest: false,
    stock: 40,
    rating: 4.7,
    reviews: 58,
    deliveryDays: "2–4",
    images: ["assets/products/toy-1.jpg", "assets/products/toy-2.jpg"],
    description: "Soft, huggable companion with an optional embroidered name tag.",
    personalization: ["Embroidered name"],
  },
  {
    id: "velvet-noir-perfume",
    name: "Velvet Noir Perfume",
    price: 3899,
    compareAt: 4299,
    category: "Beauty",
    occasions: ["Anniversary", "Birthday", "Weddings"],
    recipients: ["For Her", "For Him"],
    personalizable: false,
    trending: true,
    bestseller: false,
    newest: true,
    stock: 15,
    rating: 4.6,
    reviews: 47,
    deliveryDays: "2–4",
    images: ["assets/products/perfume-1.jpg", "assets/products/perfume-2.jpg"],
    description: "A warm, spiced fragrance in a gift-ready flacon — elegant for anniversaries.",
    personalization: [],
  },
  {
    id: "artisan-chocolate-tray",
    name: "Artisan Chocolate Tray",
    price: 1699,
    compareAt: null,
    category: "Gourmet",
    occasions: ["Birthday", "Anniversary", "Corporate", "Festive"],
    recipients: ["For Him", "For Her", "For Couples"],
    personalizable: true,
    trending: true,
    bestseller: true,
    newest: false,
    stock: 48,
    rating: 4.8,
    reviews: 152,
    deliveryDays: "1–3",
    images: ["assets/products/choc-1.jpg", "assets/products/choc-2.jpg"],
    description: "Hand-finished chocolates in a ribboned tray. Add a short printed dedication.",
    personalization: ["Printed dedication"],
  },
  {
    id: "leatherbound-journal",
    name: "Leatherbound Journal",
    price: 1599,
    compareAt: 1799,
    category: "Personalized",
    occasions: ["Birthday", "Corporate", "Weddings"],
    recipients: ["For Him", "For Her"],
    personalizable: true,
    trending: false,
    bestseller: true,
    newest: false,
    stock: 31,
    rating: 4.7,
    reviews: 88,
    deliveryDays: "3–5",
    images: ["assets/products/notebook-1.jpg", "assets/products/notebook-2.jpg"],
    description: "Soft leather journal with foil-stamped initials — ideal for corporate and personal gifts.",
    personalization: ["Foil initials", "Gift message"],
  },
  {
    id: "garden-tea-caddy",
    name: "Garden Tea Caddy",
    price: 2199,
    compareAt: null,
    category: "Gourmet",
    occasions: ["Festive", "Birthday", "Corporate"],
    recipients: ["For Her", "For Him", "For Couples"],
    personalizable: true,
    trending: false,
    bestseller: false,
    newest: true,
    stock: 27,
    rating: 4.5,
    reviews: 39,
    deliveryDays: "2–4",
    images: ["assets/products/tea-1.jpg", "assets/products/tea-2.jpg"],
    description: "A selection of garden-blend teas in a reusable caddy with optional gift tag.",
    personalization: ["Gift tag name"],
  },
];

window.LIORA_REVIEWS = [
  { name: "Ananya M.", text: "The keepsake box arrived beautifully wrapped — my sister cried happy tears.", rating: 5, product: "Curated Keepsake Box" },
  { name: "Rahul S.", text: "Corporate hampers looked premium and arrived on the exact date we needed.", rating: 5, product: "Festive Celebration Hamper" },
  { name: "Meera K.", text: "Engraving was perfect. Checkout with delivery date selection made gifting effortless.", rating: 5, product: "Pearl Drop Necklace" },
];

window.LIORA_BLOG = [
  {
    id: "anniversary-gift-ideas",
    title: "Anniversary gift ideas that feel personal",
    excerpt: "From engraved keepsakes to shared experiences in a box — ideas that say you remembered.",
    date: "2026-07-12",
    tag: "Guides",
    image: "assets/products/jewelry-1.jpg",
  },
  {
    id: "diwali-top-10",
    title: "Top 10 gifts for Diwali",
    excerpt: "Festive hampers, light, and little luxuries your hosts and teams will actually use.",
    date: "2026-06-28",
    tag: "Festive",
    image: "assets/products/hamper-1.jpg",
  },
  {
    id: "corporate-gifting-etiquette",
    title: "Corporate gifting etiquette, simplified",
    excerpt: "How to choose thoughtful bulk gifts without looking generic — branding tips included.",
    date: "2026-05-20",
    tag: "Corporate",
    image: "assets/lifestyle/corporate.jpg",
  },
];

window.formatINR = (n) =>
  new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n);

window.getProduct = (id) => window.LIORA_PRODUCTS.find((p) => p.id === id);
