#!/usr/bin/env python3
"""
Restaurant UI Kit — ThemeForest Package Generator
Generates 10 unique demos, 100+ pages, shared assets, SEO files, and documentation.
"""
from __future__ import annotations

import json
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

CDN = {
    "bootstrap_css": "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css",
    "bootstrap_js": "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js",
    "bi": "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css",
    "fa": "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css",
    "aos_css": "https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.css",
    "aos_js": "https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js",
    "swiper_css": "https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css",
    "swiper_js": "https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js",
    "gsap": "https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js",
    "scrolltrigger": "https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/ScrollTrigger.min.js",
    "glightbox_css": "https://cdn.jsdelivr.net/npm/glightbox@3.3.0/dist/css/glightbox.min.css",
    "glightbox_js": "https://cdn.jsdelivr.net/npm/glightbox@3.3.0/dist/js/glightbox.min.js",
    "isotope": "https://cdn.jsdelivr.net/npm/isotope-layout@3.0.6/dist/isotope.pkgd.min.js",
    "countup": "https://cdn.jsdelivr.net/npm/countup.js@2.8.0/dist/countUp.umd.js",
    "typed": "https://cdn.jsdelivr.net/npm/typed.js@2.1.0/dist/typed.umd.js",
    "lenis_css": "https://cdn.jsdelivr.net/npm/lenis@1.1.9/dist/lenis.css",
    "lenis_js": "https://cdn.jsdelivr.net/npm/lenis@1.1.9/dist/lenis.min.js",
    "chart": "https://cdn.jsdelivr.net/npm/chart.js@4.4.3/dist/chart.umd.min.js",
}

# Unsplash food photography (stable photo IDs)
IMG = {
    "luxury_hero": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1600&q=80",
    "luxury_dish": "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
    "italian_hero": "https://images.unsplash.com/photo-1498579150354-977475b7ea0b?w=1600&q=80",
    "pasta": "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
    "pizza": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80",
    "sushi_hero": "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=1600&q=80",
    "sushi": "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80",
    "indian_hero": "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=1600&q=80",
    "curry": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80",
    "mexican_hero": "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=1600&q=80",
    "taco": "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&q=80",
    "bbq_hero": "https://images.unsplash.com/photo-1558030006-450675393462?w=1600&q=80",
    "steak": "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&q=80",
    "seafood_hero": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=1600&q=80",
    "lobster": "https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=800&q=80",
    "cafe_hero": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1600&q=80",
    "salad": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
    "burger_hero": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1600&q=80",
    "burger": "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80",
    "bakery_hero": "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1600&q=80",
    "pastry": "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=800&q=80",
    "chef1": "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=600&q=80",
    "chef2": "https://images.unsplash.com/photo-1583394293214-28ded15ee548?w=600&q=80",
    "chef3": "https://images.unsplash.com/photo-1600565193348-f74bd3bb3b34?w=600&q=80",
    "gallery1": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
    "gallery2": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80",
    "gallery3": "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800&q=80",
    "gallery4": "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800&q=80",
    "gallery5": "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&q=80",
    "gallery6": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80",
    "blog1": "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    "blog2": "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&q=80",
    "blog3": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    "interior": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&q=80",
    "wine": "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80",
    "dessert": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
    "coffee": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    "avatar": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
}

DEMOS = [
    {
        "id": "demo-01-luxury",
        "name": "Luxury Fine Dining",
        "brand": "Maison Étoile",
        "tagline": "Michelin-Starred Elegance",
        "fonts": "Cormorant+Garamond:wght@400;500;600;700|Montserrat:wght@300;400;500;600;700|Great+Vibes",
        "hero_img": IMG["luxury_hero"],
        "dish_img": IMG["luxury_dish"],
        "layout": "luxury",
        "nav_style": "transparent-centered",
        "hero_style": "fullscreen-slider",
        "footer_style": "centered-luxury",
        "menu": [
            ("Truffle Risotto", 48, "mains", "veg", 4.9),
            ("Wagyu Tenderloin", 92, "mains", "nonveg", 5.0),
            ("Oyster Rockefeller", 36, "starters", "nonveg", 4.8),
            ("Lobster Thermidor", 78, "mains", "nonveg", 4.9),
            ("Champagne Jelly", 22, "desserts", "veg", 4.7),
            ("Caviar Service", 120, "starters", "nonveg", 5.0),
            ("Duck à l'Orange", 64, "mains", "nonveg", 4.8),
            ("Chocolate Soufflé", 28, "desserts", "veg", 4.9),
        ],
        "categories": ["Starters", "Mains", "Desserts", "Wine Pairing"],
        "stats": [(12, "Years"), (3, "Michelin Stars"), (48, "Signature Dishes"), (15, "Sommelier Picks")],
        "chefs": [("Chef Amélie Laurent", "Executive Chef"), ("Marco Bellini", "Pastry Chef"), ("Sofia Chen", "Sommelier")],
    },
    {
        "id": "demo-02-italian",
        "name": "Italian Restaurant",
        "brand": "Trattoria Bella",
        "tagline": "Nonna's Recipes, Modern Soul",
        "fonts": "Playfair+Display:wght@400;500;600;700|Lato:wght@300;400;700",
        "hero_img": IMG["italian_hero"],
        "dish_img": IMG["pasta"],
        "layout": "italian",
        "nav_style": "solid-split",
        "hero_style": "split-hero",
        "footer_style": "italian-columns",
        "menu": [
            ("Spaghetti Carbonara", 22, "pasta", "nonveg", 4.9),
            ("Margherita Pizza", 18, "pizza", "veg", 4.8),
            ("Osso Buco", 34, "mains", "nonveg", 4.9),
            ("Tiramisu Classico", 12, "desserts", "veg", 5.0),
            ("Bruschetta Trio", 14, "starters", "veg", 4.7),
            ("Seafood Linguine", 28, "pasta", "nonveg", 4.8),
            ("Bistecca Fiorentina", 55, "mains", "nonveg", 4.9),
            ("Panna Cotta", 11, "desserts", "veg", 4.6),
        ],
        "categories": ["Antipasti", "Pasta", "Pizza", "Secondi", "Dolci"],
        "stats": [(1985, "Est."), (40, "Pasta Shapes"), (120, "Seats"), (8, "Chefs")],
        "chefs": [("Nonna Rosa", "Founder"), ("Luca Romano", "Head Chef"), ("Giulia Conti", "Pizza Chef")],
    },
    {
        "id": "demo-03-sushi",
        "name": "Japanese Sushi",
        "brand": "Sakura Omote",
        "tagline": "Precision. Season. Harmony.",
        "fonts": "Zen+Maru+Gothic:wght@400;500;700|Noto+Sans+JP:wght@300;400;500;700",
        "hero_img": IMG["sushi_hero"],
        "dish_img": IMG["sushi"],
        "layout": "sushi",
        "nav_style": "minimal-side",
        "hero_style": "video-zen",
        "footer_style": "minimal-zen",
        "menu": [
            ("Omakase Set", 95, "omakase", "nonveg", 5.0),
            ("Dragon Roll", 24, "rolls", "nonveg", 4.8),
            ("Salmon Nigiri", 8, "nigiri", "nonveg", 4.9),
            ("Toro Sashimi", 32, "sashimi", "nonveg", 5.0),
            ("Miso Ramen", 18, "hot", "nonveg", 4.7),
            ("Veggie Tempura", 16, "hot", "veg", 4.6),
            ("Matcha Mochi", 10, "desserts", "veg", 4.8),
            ("Sake Flight", 28, "drinks", "veg", 4.9),
        ],
        "categories": ["Omakase", "Nigiri", "Rolls", "Sashimi", "Hot"],
        "stats": [(200, "Daily Fish"), (1, "Itamae"), (35, "Seats"), (12, "Sake Labels")],
        "chefs": [("Kenji Watanabe", "Itamae"), ("Yuki Tanaka", "Sous Chef"), ("Aiko Mori", "Pastry")],
    },
    {
        "id": "demo-04-indian",
        "name": "Indian Restaurant",
        "brand": "Spice Route",
        "tagline": "A Journey Across Flavors",
        "fonts": "Tiro+Devanagari+Hindi&family=Poppins:wght@300;400;500;600;700",
        "hero_img": IMG["indian_hero"],
        "dish_img": IMG["curry"],
        "layout": "indian",
        "nav_style": "ornate-top",
        "hero_style": "cinematic-overlay",
        "footer_style": "rich-columns",
        "menu": [
            ("Butter Chicken", 22, "mains", "nonveg", 4.9),
            ("Paneer Tikka", 16, "starters", "veg", 4.8),
            ("Lamb Biryani", 26, "mains", "nonveg", 5.0),
            ("Dal Makhani", 14, "mains", "veg", 4.7),
            ("Masala Dosa", 12, "south", "veg", 4.8),
            ("Tandoori Platter", 32, "starters", "nonveg", 4.9),
            ("Gulab Jamun", 8, "desserts", "veg", 4.9),
            ("Mango Lassi", 6, "drinks", "veg", 4.8),
        ],
        "categories": ["Tandoor", "Curries", "Biryani", "Breads", "Sweets"],
        "stats": [(50, "Spices"), (25, "Years"), (180, "Dishes"), (4, "Regions")],
        "chefs": [("Rajesh Kapoor", "Executive Chef"), ("Priya Sharma", "Tandoor Chef"), ("Anil Mehta", "Pastry")],
    },
    {
        "id": "demo-05-mexican",
        "name": "Mexican Restaurant",
        "brand": "Casa Fuego",
        "tagline": "Bold Fire. Bright Fiesta.",
        "fonts": "Abril+Fatface&family=Nunito:wght@300;400;600;700;800",
        "hero_img": IMG["mexican_hero"],
        "dish_img": IMG["taco"],
        "layout": "mexican",
        "nav_style": "bold-color",
        "hero_style": "diagonal-split",
        "footer_style": "fiesta",
        "menu": [
            ("Street Tacos", 14, "tacos", "nonveg", 4.9),
            ("Guacamole Fresco", 10, "starters", "veg", 4.8),
            ("Mole Poblano", 24, "mains", "nonveg", 5.0),
            ("Carnitas Burrito", 16, "mains", "nonveg", 4.7),
            ("Elote Cups", 8, "starters", "veg", 4.8),
            ("Churros & Chocolate", 9, "desserts", "veg", 4.9),
            ("Margarita Flight", 22, "drinks", "veg", 4.8),
            ("Quesadilla Verde", 13, "mains", "veg", 4.6),
        ],
        "categories": ["Tacos", "Moles", "Antojitos", "Postres", "Agave"],
        "stats": [(12, "Salsas"), (8, "Mezcal"), (90, "Seats"), (2010, "Est.")],
        "chefs": [("Elena Vargas", "Chef de Cuisine"), ("Diego Ruiz", "Grill Master"), ("Camila Soto", "Pastry")],
    },
    {
        "id": "demo-06-bbq",
        "name": "BBQ & Steak House",
        "brand": "Smoke & Ember",
        "tagline": "Low & Slow. Fire & Iron.",
        "fonts": "Oswald:wght@400;500;600;700|Source+Sans+3:wght@300;400;600;700",
        "hero_img": IMG["bbq_hero"],
        "dish_img": IMG["steak"],
        "layout": "bbq",
        "nav_style": "industrial",
        "hero_style": "fullbleed-cta",
        "footer_style": "industrial",
        "menu": [
            ("Tomahawk Steak", 78, "steaks", "nonveg", 5.0),
            ("Brisket Plate", 32, "bbq", "nonveg", 4.9),
            ("Baby Back Ribs", 28, "bbq", "nonveg", 4.8),
            ("Smoked Wings", 16, "starters", "nonveg", 4.7),
            ("Loaded Potato", 12, "sides", "veg", 4.6),
            ("Burnt Ends", 24, "bbq", "nonveg", 4.9),
            ("Apple Cobbler", 10, "desserts", "veg", 4.8),
            ("Bourbon Flight", 26, "drinks", "veg", 4.9),
        ],
        "categories": ["Steaks", "Smoked BBQ", "Sides", "Bourbon"],
        "stats": [(14, "Hour Smoke"), (45, "Day Dry Age"), (200, "Seats"), (6, "Pitmasters")],
        "chefs": [("Jake Harlan", "Pitmaster"), ("Tina Brooks", "Grill Chef"), ("Sam Ortega", "Sous")],
    },
    {
        "id": "demo-07-seafood",
        "name": "Seafood Restaurant",
        "brand": "Azure Harbor",
        "tagline": "Ocean to Table, Daily",
        "fonts": "Libre+Baskerville:wght@400;700|DM+Sans:wght@300;400;500;600;700",
        "hero_img": IMG["seafood_hero"],
        "dish_img": IMG["lobster"],
        "layout": "seafood",
        "nav_style": "wave-top",
        "hero_style": "ocean-parallax",
        "footer_style": "harbor",
        "menu": [
            ("Grilled Lobster", 68, "mains", "nonveg", 5.0),
            ("Oysters Raw Bar", 24, "raw", "nonveg", 4.9),
            ("Cioppino Stew", 32, "mains", "nonveg", 4.8),
            ("Fish & Chips", 18, "classics", "nonveg", 4.7),
            ("Tuna Tartare", 22, "starters", "nonveg", 4.9),
            ("Clam Chowder", 14, "soups", "nonveg", 4.6),
            ("Key Lime Pie", 11, "desserts", "veg", 4.8),
            ("Coastal Spritz", 14, "drinks", "veg", 4.7),
        ],
        "categories": ["Raw Bar", "Grilled", "Stews", "Classics"],
        "stats": [(6, "AM Catch"), (40, "Boats"), (110, "Seats"), (18, "Wines")],
        "chefs": [("Captain Nora Wells", "Executive Chef"), ("Leo Park", "Raw Bar"), ("Mia Costa", "Pastry")],
    },
    {
        "id": "demo-08-cafe",
        "name": "Organic Cafe",
        "brand": "Green Leaf Kitchen",
        "tagline": "Farm Fresh. Feel Good.",
        "fonts": "Fraunces:opsz,wght@9..144,400;600;700|Karla:wght@300;400;500;600;700",
        "hero_img": IMG["cafe_hero"],
        "dish_img": IMG["salad"],
        "layout": "cafe",
        "nav_style": "soft-pill",
        "hero_style": "soft-split",
        "footer_style": "organic",
        "menu": [
            ("Buddha Bowl", 16, "bowls", "veg", 4.9),
            ("Avocado Toast", 12, "breakfast", "veg", 4.8),
            ("Kale Caesar", 14, "salads", "veg", 4.7),
            ("Matcha Latte", 6, "drinks", "veg", 4.8),
            ("Grain Power Plate", 18, "bowls", "veg", 4.9),
            ("Berry Parfait", 9, "breakfast", "veg", 4.6),
            ("Cold Press Juice", 7, "drinks", "veg", 4.7),
            ("Vegan Brownie", 8, "desserts", "veg", 4.8),
        ],
        "categories": ["Breakfast", "Bowls", "Salads", "Juices", "Bakes"],
        "stats": [(100, "% Organic"), (12, "Farms"), (60, "Seats"), (0, "Waste Goal")],
        "chefs": [("Harper Quinn", "Head Chef"), ("Noah Green", "Nutritionist"), ("Ivy Lane", "Baker")],
    },
    {
        "id": "demo-09-fastfood",
        "name": "Fast Food & Burger",
        "brand": "Bolt Burger",
        "tagline": "Smash. Stack. Satisfied.",
        "fonts": "Bebas+Neue&family=Manrope:wght@300;400;500;600;700;800",
        "hero_img": IMG["burger_hero"],
        "dish_img": IMG["burger"],
        "layout": "fastfood",
        "nav_style": "app-bar",
        "hero_style": "product-pop",
        "footer_style": "app-promo",
        "menu": [
            ("Classic Smash", 11, "burgers", "nonveg", 4.9),
            ("Double Bolt", 15, "burgers", "nonveg", 5.0),
            ("Crispy Chicken", 12, "chicken", "nonveg", 4.8),
            ("Loaded Fries", 7, "sides", "veg", 4.7),
            ("Veggie Stack", 12, "burgers", "veg", 4.6),
            ("Milkshake Trio", 8, "drinks", "veg", 4.9),
            ("Onion Rings", 6, "sides", "veg", 4.5),
            ("Kids Combo", 9, "kids", "nonveg", 4.8),
        ],
        "categories": ["Burgers", "Chicken", "Sides", "Shakes", "Kids"],
        "stats": [(5, "Min Grill"), (30, "Locations"), (1, "M+ Served"), (24, "Hours")],
        "chefs": [("Max Rivera", "Culinary Lead"), ("Zoe Kim", "Menu R&D"), ("Ben Cole", "Ops Chef")],
    },
    {
        "id": "demo-10-bakery",
        "name": "Bakery & Coffee Shop",
        "brand": "Crumb & Steam",
        "tagline": "Baked at Dawn. Brewed with Care.",
        "fonts": "Bodoni+Moda:opsz,wght@6..96,400;600;700|Outfit:wght@300;400;500;600;700",
        "hero_img": IMG["bakery_hero"],
        "dish_img": IMG["pastry"],
        "layout": "bakery",
        "nav_style": "warm-minimal",
        "hero_style": "editorial",
        "footer_style": "bakery",
        "menu": [
            ("Sourdough Loaf", 8, "bread", "veg", 4.9),
            ("Butter Croissant", 5, "pastry", "veg", 5.0),
            ("Flat White", 4.5, "coffee", "veg", 4.8),
            ("Berry Danish", 6, "pastry", "veg", 4.7),
            ("Chocolate Babka", 7, "bread", "veg", 4.9),
            ("Cinnamon Roll", 5.5, "pastry", "veg", 4.8),
            ("Pour-Over Flight", 9, "coffee", "veg", 4.9),
            ("Lemon Tart", 6.5, "desserts", "veg", 4.7),
        ],
        "categories": ["Bread", "Pastry", "Coffee", "Cakes", "Seasonal"],
        "stats": [(4, "AM Bake"), (18, "Beans"), (40, "Seats"), (7, "Days Fresh")],
        "chefs": [("Clara Whit", "Head Baker"), ("Owen Brooks", "Barista Lead"), ("Lena Moss", "Pastry")],
    },
]

# Shared page catalog (100+)
PAGES = [
    # Main
    ("about", "About", "main"),
    ("our-story", "Our Story", "main"),
    ("our-chef", "Our Chef", "main"),
    ("team", "Team", "main"),
    ("menu", "Menu", "main"),
    ("special-menu", "Special Menu", "main"),
    ("food-categories", "Food Categories", "main"),
    ("reservation", "Reservation", "main"),
    ("online-booking", "Online Booking", "main"),
    ("events", "Events", "main"),
    ("gallery", "Gallery", "main"),
    ("services", "Services", "main"),
    ("pricing", "Pricing", "main"),
    ("testimonials", "Testimonials", "main"),
    ("faqs", "FAQs", "main"),
    ("contact", "Contact", "main"),
    ("location", "Location", "main"),
    ("blog-grid", "Blog Grid", "main"),
    ("blog-list", "Blog List", "main"),
    ("blog-details", "Blog Details", "main"),
    ("404", "404 Not Found", "system"),
    ("coming-soon", "Coming Soon", "system"),
    ("maintenance", "Maintenance", "system"),
    ("privacy-policy", "Privacy Policy", "legal"),
    ("terms", "Terms of Service", "legal"),
    ("cookie-policy", "Cookie Policy", "legal"),
    # Premium additional
    ("career", "Careers", "corporate"),
    ("gift-cards", "Gift Cards", "promo"),
    ("membership", "Membership", "promo"),
    ("loyalty-program", "Loyalty Program", "promo"),
    ("delivery-information", "Delivery Information", "misc"),
    ("takeaway", "Takeaway", "misc"),
    ("franchise", "Franchise", "corporate"),
    ("press", "Press", "corporate"),
    ("media", "Media Kit", "corporate"),
    ("awards", "Awards", "corporate"),
    ("partners", "Partners", "corporate"),
    ("corporate-dining", "Corporate Dining", "catering"),
    ("wedding-catering", "Wedding Catering", "catering"),
    ("birthday-catering", "Birthday Catering", "catering"),
    ("private-events", "Private Events", "catering"),
    ("restaurant-chain", "Restaurant Chain", "corporate"),
    ("investor-relations", "Investor Relations", "corporate"),
    ("sustainability", "Sustainability", "corporate"),
    ("csr", "CSR", "corporate"),
    ("food-safety", "Food Safety", "misc"),
    ("nutrition", "Nutrition", "misc"),
    ("chef-profile", "Chef Profile", "main"),
    ("customer-stories", "Customer Stories", "main"),
    ("video-gallery", "Video Gallery", "main"),
    ("instagram-feed", "Instagram Feed", "main"),
    ("recipes", "Recipes", "blog"),
    ("news", "News", "blog"),
    ("seasonal-offers", "Seasonal Offers", "promo"),
    ("coupons", "Coupons", "promo"),
    ("special-deals", "Special Deals", "promo"),
    ("wine-collection", "Wine Collection", "collections"),
    ("coffee-collection", "Coffee Collection", "collections"),
    ("dessert-collection", "Dessert Collection", "collections"),
    ("kids-menu", "Kids Menu", "menu"),
    ("breakfast-menu", "Breakfast Menu", "menu"),
    ("lunch-menu", "Lunch Menu", "menu"),
    ("dinner-menu", "Dinner Menu", "menu"),
    ("festival-menu", "Festival Menu", "menu"),
    ("reservation-success", "Reservation Success", "booking"),
    ("reservation-failed", "Reservation Failed", "booking"),
    ("contact-success", "Contact Success", "system"),
    ("newsletter-success", "Newsletter Success", "system"),
    ("search-results", "Search Results", "misc"),
    ("wishlist", "Wishlist", "ui"),
    ("favorite-meals", "Favorite Meals", "ui"),
    ("compare-meals", "Compare Meals", "ui"),
    ("order-tracking", "Order Tracking", "ui"),
    ("invoice", "Invoice", "ui"),
    ("faq-category", "FAQ Category", "main"),
    ("restaurant-timeline", "Restaurant Timeline", "main"),
    ("restaurant-history", "Restaurant History", "main"),
    ("awards-timeline", "Awards Timeline", "main"),
    ("location-finder", "Location Finder", "misc"),
    ("store-locator", "Store Locator", "misc"),
    ("branches", "Branches", "misc"),
    ("branch-details", "Branch Details", "misc"),
    ("event-details", "Event Details", "main"),
    ("book-event", "Book Event", "booking"),
    ("customer-dashboard", "Customer Dashboard", "dashboard"),
    ("reservation-history", "Reservation History", "dashboard"),
    ("profile", "Profile", "dashboard"),
    ("settings", "Settings", "dashboard"),
    ("notifications", "Notifications", "dashboard"),
    ("review-submission", "Submit a Review", "ui"),
    ("thank-you", "Thank You", "system"),
    ("landing", "Landing Page", "promo"),
    ("promotion-landing", "Promotion Landing", "promo"),
    ("black-friday-landing", "Black Friday Landing", "promo"),
    ("christmas-landing", "Christmas Landing", "promo"),
    ("new-year-landing", "New Year Landing", "promo"),
    ("valentine-landing", "Valentine Landing", "promo"),
    ("mothers-day-landing", "Mother's Day Landing", "promo"),
    ("app-landing", "Restaurant App Landing", "promo"),
    ("saas-landing", "Restaurant SaaS Landing", "promo"),
    ("pos-landing", "Restaurant POS Landing", "promo"),
    ("crm-landing", "Restaurant CRM Landing", "promo"),
    ("delivery-landing", "Delivery Landing", "promo"),
    ("franchise-landing", "Franchise Landing", "promo"),
    ("booking-landing", "Booking Landing", "promo"),
    ("membership-landing", "Membership Landing", "promo"),
    ("loyalty-landing", "Loyalty Landing", "promo"),
    ("mobile-app-landing", "Mobile App Landing", "promo"),
    ("admin-preview", "Admin Preview", "dashboard"),
    ("analytics", "Analytics UI", "dashboard"),
    ("reports", "Reports UI", "dashboard"),
    ("charts", "Charts UI", "dashboard"),
    ("statistics", "Statistics UI", "dashboard"),
    ("components-showcase", "Components Showcase", "ui"),
    ("login", "Login", "auth"),
    ("signup", "Sign Up", "auth"),
    ("forgot-password", "Forgot Password", "auth"),
]

